[tool.robotpy]

robotpy_version = "2025.3.1.1"

robotpy_extras = [
    "apriltag",
    "commands2"
]

# Other pip packages to install
requires = [
    "robotpy-pathplannerlib==2025.2.3",
    "phoenix6==25.3.0"
]
